# Generated by Django 4.2.5 on 2023-10-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_client_remove_seller_user_remove_basket_buyer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="purchases",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="client",
            name="sales",
            field=models.IntegerField(default=0),
        ),
    ]
