# Generated by Django 4.1.4 on 2023-10-18 14:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_client_purchases_alter_client_sales"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product_Img",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default.png", upload_to="products/images"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="empty"),
        ),
        migrations.AddField(
            model_name="product",
            name="published_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 10, 18, 14, 43, 29, 911681, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product_img",
            ),
        ),
    ]
