# Generated by Django 4.1.4 on 2023-10-25 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_img_product_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("name_cat",), "verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="published_date",
            new_name="creater_date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="client",
        ),
        migrations.RemoveField(
            model_name="product",
            name="images",
        ),
        migrations.AddField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                default=-23,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.client",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="products/images"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=-2023),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Product_Img",
        ),
    ]
